package io.github.thediscprog.anvil.annotations

import scala.annotation.StaticAnnotation

final case class PrimaryKey(
    keyType: PrimaryKeyType,
    columns: List[String],
    autoGenerated: Boolean
) extends StaticAnnotation
